server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      connection-init-sql: SET TIME ZONE 'America/Sao_Paulo'
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
           auto: none
     
