
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service_order
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
       show_sql: true
       format_sql: true
 
authentication:
  basic: ZmlydHN1c2VyOmZZS2U4UTNhQm50VnF1UDJLM3Y3aFRNRXk4QkhZeEp6